# Github actions by default aborted the entire job if one step is failed.
# We can change this behaviour by this implementation:

# Conditional IF:
# if:steps.run-ido-test.outcome
# steps - is a built in api for refrencing other steps in a job.
# outcome - is the result of the step (failure / success / cancelled / skipped)

# Special Conditional Functions:
# failure() - return true when any previous step / job failed
# success() - return true when every single step / job done successfully
# cancelled() - return true if the workflow has been canclled
# always() - return true always 

name: Website Deployment
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        id: run-ido-test  # We can add id field to any step for refrencing
        run: npm run test
      - name: Upload test report
      # NOTICE: steps.run-ido-test.outcome == 'failure' alone is not sufficuent for continue the step if the last step is failed (like we want for the example) 
      # For overwritten the default behaviour of Github Action we have to add the failure() method
        if: failure() && steps.run-ido-test.outcome == 'failure'
        # Other possible is to use:
        # continue-on-error: true   
        # NOTICE: In both cases, the next step will continue even if the prior step has failed.continue-on-error: 
          # The diffreneces between these methods:
          # 1. in the IF option - the entire JOB still consider as failed (beacuse the test failed) 
          # 2. in the continue-on-error - the entire JOB will consider as success (even if case of failure in prior step)
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
          # => The result is that the file that created by 'npm run test' is upload to Github even if the tests has failed 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    # This job will run only if one the other jobs will fail
    # notice that we have to set the needs keyword cause jobs runs parallel (In this point there is no any failure job or steps to handle)
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: |
          echo "Something went worng"
      
